# Generated by Django 3.2.9 on 2021-12-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaudio',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
